### ISSUE TITLE
Symfony 2.7 incompatibility

### ISSUE THREAD

**Issue by leechao** [FriendsOfSymfony/FOSRestBundle#1062]
Hi, 
I have an issue upgrading my project to Symfony 2.7.0 (previously on 2.6.9), using PHP 5.5.20 and the 1.6.* version of FOSRestBundle.

Here is my configuraiton 
```
fos_rest:
    view:
        formats:
            json:           true
    routing_loader:
        default_format:     json
        include_format:     true
    param_fetcher_listener:
        enabled:            true
        force:              true
    body_listener:          true
    allowed_methods_listener: true
```

Apparently, setting 'allowed_methods_listener' to 'true' seems to break the developpement environment as I can't display any WebProfiler pages or any error pages anymore. If I remove this option from my config.yml or if I use the default configuration, everything goes back to normal.

Also, all methods using the bundle return an error 500 since the response doesn't contain any data whether I use the "fos_rest" default configuration or the custom configuration above.

**Comment by lsmith77** [comment]
do you have 1.6.0 or 1.6.1?

**Comment by leechao** [comment]
I tested both versions and neither of them works.

**Comment by lsmith77** [comment]
does this change fix the issue?

https://github.com/FriendsOfSymfony/FOSRestBundle/commit/81966a05ea92c87d21604a38ba867ebefa439802

**Comment by leechao** [comment]
It doesn't break error pages and WebProfiler pages anymore. However, my REST actions still return 500 errors.

**Comment by lsmith77** [comment]
can you give me more details? for example have a look in the profiler to tell me more information about the exception you are getting

**Comment by leechao** [comment]
There is no exception thrown, that's the problem. I get the error 500 because apparently, the response does not contain any data. Here's the end of my action in my controller:

```
        $this->response = array(
            "status" => $dataRepository->getStatus(),
            "last_update" => (is_null($lastUpdate) ? "null" : $lastUpdate->format('Y-m-d H:i:s'))
        );
        $view = View::create();
        $view->setStatusCode(200)
            ->setData($this->response)
            ->setFormat("json");
        $return = $this->get('fos_rest.view_handler')->handle($view);
        $logger->info($return);
        return $return;
```
Here's the response logged that should be returned. Seems pretty valid to me.
```
app.INFO: HTTP/1.0 200 OK Cache-Control: no-cache Content-Type:  application/json Date:          Thu, 11 Jun 2015 09:47:18 GMT  {"status":"ok","last_update":"2015-05-29 10:38:53"} [] []
```

**Comment by lsmith77** [comment]
hmm this sounds really strange .. the code looks fine and I have no idea what change could cause this to not work. I fear you will need to debug this some more yourself by looking at the ``ViewHandler`` class ..

**Comment by leechao** [comment]
I did, but as you can see the class returns a valid response, 

```
object(Symfony\Component\HttpFoundation\Response)[1326]
  public 'headers' => 
    object(Symfony\Component\HttpFoundation\ResponseHeaderBag)[1322]
      protected 'computedCacheControl' => 
        array (size=1)
          'no-cache' => boolean true
      protected 'cookies' => 
        array (size=0)
          empty
      protected 'headerNames' => 
        array (size=3)
          'cache-control' => string 'Cache-Control' (length=13)
          'content-type' => string 'Content-Type' (length=12)
          'date' => string 'Date' (length=4)
      protected 'headers' => 
        array (size=3)
          'cache-control' => 
            array (size=1)
              0 => string 'no-cache' (length=8)
          'content-type' => 
            array (size=1)
              0 => string 'application/json' (length=16)
          'date' => 
            array (size=1)
              0 => string 'Thu, 11 Jun 2015 11:31:18 GMT' (length=29)
      protected 'cacheControl' => 
        array (size=0)
          empty
  protected 'content' => string '{"status":"ok","last_update":"2015-05-29 10:38:53"}' (length=51)
  protected 'version' => string '1.0' (length=3)
  protected 'statusCode' => int 200
  protected 'statusText' => string 'OK' (length=2)
  protected 'charset' => null
``` 

My guess is that the problem lies somewhere else.

**Comment by leechao** [comment]
Just a quick update to say that the problem seems to occur when you use $this->getDoctrine()-> **getRepository()**. If I remove all those calls and set a static array as a response, then it works. 

Very strange since these DB queries return the expected results, don't throw any exception and leave no errors or warning in the logs.

**Comment by leechao** [comment]
The problem is fixed with the version 2.7.1 of Symfony.

**Comment by rubiodamian** [comment]
this seems not resolved.
I'm having the same issue right now!
when the controller returns a string the response is a json and when it returns an entity the request freeze and return a 500 http error

**Comment by rubiodamian** [comment]
solved using http://npmasters.com/2012/11/25/Symfony2-Rest-FOSRestBundle.html

**Comment by lsmith77** [comment]
@rubiodamian if there is anything we should add to the docs from there .. can you mention it here .. or better yet open a PR with the additions?
