### ISSUE TITLE
Non-existent parameter format_listener

### ISSUE THREAD

**Issue by pilotepro** [FriendsOfSymfony/FOSRestBundle#1179]
Hi,

Since the update from 1.7.1 to dev-master version using Symfony 2.7, format listener is no longer working. Without any modifications of the config I now get the following error when I clear the cache :

```
[Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException]
You have requested a non-existent parameter "fos_rest.format_listener.rules".
```

And when I go to the API :
```
InvalidArgumentException in ContainerBuilder.php line 868:
The service definition "fos_rest.exception_format_negotiator" does not exist.
```

Here is my config of the bundle :
```
fos_rest:
    param_fetcher_listener:    force
    body_listener:             true
    allowed_methods_listener:  true
    disable_csrf_role:         IS_AUTHENTICATED_ANONYMOUSLY
    routing_loader:
        default_format:  null
        include_format:  false
    format_listener:
        rules:
            - { path: '^/', priorities: [ 'json', 'xml' ], fallback_format: json, prefer_extension: false }
    view:
        view_response_listener: force
        formats:
            json: true
            xml:  true
    serializer:
        serialize_null:         true
```

Thank you.

**Comment by lsmith77** [comment]
did you read the UPGRADING guide? master is a considerable refactoring which will break BC in many ways

**Comment by pilotepro** [comment]
Thank you for your reply, I have read the UPGRADING guide and I don't see a change that can break my configuration and according to the documentation my configuration is still good. So I don't understand why it doesn't work. So what I need to do to make it work exactly ?

PS : All my code works with this new version and I no longer have errors if I disable format_listener but I need format_listener to work.

**Comment by xabbuh** [comment]
@pilotepro Can you please check which part of the code is refering to the `fos_rest.format_listener.rules` parameter? And did you try to delete the cache manually instead of using the `cache:clear` command?

@lsmith77 Unfortunately, I forgot to update the upgrade file in #1158. I will take a look at it.

**Comment by pilotepro** [comment]
I don't know this happens when I clear the cache with the command "php app/console cache:clear --env=prod -v".

Here is the debug output when I clear the cache :
```
Clearing the cache for the prod environment with debug false                                                   
  Clearing outdated warmup directory
  Warming up cache


  [Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException]                                 
  You have requested a non-existent parameter "fos_rest.format_listener.rules".                                


Exception trace:
 () at C:\Program Files\Wamp Server\www\Unanimita\API\vendor\symfony\symfony\src\Symfony\Component\DependencyIn
jection\ParameterBag\ParameterBag.php:106                                                                      
 Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->get() at C:\Program Files\Wamp Server\www\Una
nimita\API\app\bootstrap.php.cache:2063                                                                        
 Symfony\Component\DependencyInjection\Container->getParameter() at C:\Program Files\Wamp Server\www\Unanimita\
API\vendor\friendsofsymfony\rest-bundle\DependencyInjection\Compiler\FormatListenerRulesPass.php:49            
 FOS\RestBundle\DependencyInjection\Compiler\FormatListenerRulesPass->process() at C:\Program Files\Wamp Server
\www\Unanimita\API\vendor\symfony\symfony\src\Symfony\Component\DependencyInjection\Compiler\Compiler.php:117  
 Symfony\Component\DependencyInjection\Compiler\Compiler->compile() at C:\Program Files\Wamp Server\www\Unanimi
ta\API\vendor\symfony\symfony\src\Symfony\Component\DependencyInjection\ContainerBuilder.php:614               
 Symfony\Component\DependencyInjection\ContainerBuilder->compile() at C:\Program Files\Wamp Server\www\Unanimit
a\API\app\bootstrap.php.cache:2633                                                                             
 Symfony\Component\HttpKernel\Kernel->initializeContainer() at C:\Program Files\Wamp Server\www\Unanimita\API\a
pp\bootstrap.php.cache:2411                                                                                    
 Symfony\Component\HttpKernel\Kernel->boot() at C:\Program Files\Wamp Server\www\Unanimita\API\vendor\symfony\s
ymfony\src\Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand.php:128                                    
 Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->warmup() at C:\Program Files\Wamp Server\www\Unanimi
ta\API\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand.php:90              
 Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->execute() at C:\Program Files\Wamp Server\www\Unanim
ita\API\vendor\symfony\symfony\src\Symfony\Component\Console\Command\Command.php:259                           
 Symfony\Component\Console\Command\Command->run() at C:\Program Files\Wamp Server\www\Unanimita\API\vendor\symf
ony\symfony\src\Symfony\Component\Console\Application.php:886                                                  
 Symfony\Component\Console\Application->doRunCommand() at C:\Program Files\Wamp Server\www\Unanimita\API\vendor
\symfony\symfony\src\Symfony\Component\Console\Application.php:195                                             
 Symfony\Component\Console\Application->doRun() at C:\Program Files\Wamp Server\www\Unanimita\API\vendor\symfon
y\symfony\src\Symfony\Bundle\FrameworkBundle\Console\Application.php:96                                        
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at C:\Program Files\Wamp Server\www\Unanimita\API\
vendor\symfony\symfony\src\Symfony\Component\Console\Application.php:126                                       
 Symfony\Component\Console\Application->run() at C:\Program Files\Wamp Server\www\Unanimita\API\app\console:27 

cache:clear [--no-warmup] [--no-optional-warmers]
```
 But I don't get the error if I disable format_listener like this :
```
fos_rest:
    [...]
    format_listener:
        enabled:             false
        rules:
            - { path: '^/', priorities: [ 'json', 'xml' ], fallback_format: json, prefer_extension: false }
    [...]
```
 And yes I have done both, with command line and manually with deleting cache folder content and log file.

**Comment by xabbuh** [comment]
@pilotepro Thanks for the stack trace. This is indeed a bug. I will have a look at it.

**Comment by Ener-Getick** [comment]
@xabbuh It seems that it come from ``FormatListenerRulesPass::49``. 
I think this is linked to #1158. (https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1158/files#diff-ffb88a00253e285e14e0d32ef5423cd1L163)

We have to pass the rules to ``FormatListenerRulesPass``. Maybe a static variable or redefining ``fos_rest.format_listener.rules`` in the container.

**Comment by xabbuh** [comment]
@Ener-Getick Exactly, though I am not quite sure yet what would be the best solution (by the way, we should think of adding a test when fixing it to prevent regressions in the future).

**Comment by Ener-Getick** [comment]
A functional test that activates all the ``FOSRestBundle`` features would be good to begin.

**Comment by pilotepro** [comment]
Hello,
Thank you for your help, PR #1180 fixes the first error but not the second one even though config remains the same, when I clear the cache (same command as above) and on the API directly too.

Here is the debug output :
```
[Symfony\Component\DependencyInjection\Exception\InvalidArgumentException]
  The service definition "fos_rest.exception_format_negotiator" does not exist.

Exception trace:
 () at C:\Program Files\Wamp Server\www\Unanimita\API\vendor\symfony\symfony\src\Symfony\Component\DependencyInjection\ContainerBuilder.php:868
 Symfony\Component\DependencyInjection\ContainerBuilder->getDefinition() at C:\Program Files\Wamp Server\www\Unanimita\API\vendor\friendsofsymfony\rest-bundle\DependencyInjection\Compiler\FormatListenerRulesPass.php:77
 FOS\RestBundle\DependencyInjection\Compiler\FormatListenerRulesPass->addRule() at C:\Program Files\Wamp Server\www\Unanimita\API\vendor\friendsofsymfony\rest-bundle\DependencyInjection\Compiler\FormatListenerRulesPass.php:51
 FOS\RestBundle\DependencyInjection\Compiler\FormatListenerRulesPass->process() at C:\Program Files\Wamp Server\www\Unanimita\API\vendor\symfony\symfony\src\Symfony\Component\DependencyInjection\Compiler\Compiler.php:117
 Symfony\Component\DependencyInjection\Compiler\Compiler->compile() at C:\Program Files\Wamp Server\www\Unanimita\API\vendor\symfony\symfony\src\Symfony\Component\DependencyInjection\ContainerBuilder.php:614
 Symfony\Component\DependencyInjection\ContainerBuilder->compile() at C:\Program Files\Wamp Server\www\Unanimita\API\app\bootstrap.php.cache:2633
 Symfony\Component\HttpKernel\Kernel->initializeContainer() at C:\Program Files\Wamp Server\www\Unanimita\API\app\bootstrap.php.cache:2411
 Symfony\Component\HttpKernel\Kernel->boot() at C:\Program Files\Wamp Server\www\Unanimita\API\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Console\Application.php:70
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at C:\Program Files\Wamp Server\www\Unanimita\API\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php:126
 Symfony\Component\Console\Application->run() at C:\Program Files\Wamp Server\www\Unanimita\API\app\console:27
```

**Comment by Ener-Getick** [comment]
#1184 should fix this.

**Comment by pilotepro** [comment]
With PR #1184 I no longer have errors, but format_listener still doesn't work. When I set Accept header to "application/xml" the API output is still in "application/json", even though with 1.7.1 version of FOSRestBundle it's working.

**Comment by Ener-Getick** [comment]
If you use format in your priorities (``json``,  ``xml``, ...)  you have to define their corresponding mime types in 2.0.
Normally, only text/xml is auto detected in 2.0.

**Comment by pilotepro** [comment]
The format_listener is now working.

Thank you all for your help.
