### ISSUE TITLE
[Symfony 4.4] Remaining deprecation notices

### ISSUE THREAD

**Issue by XWB** [FriendsOfSymfony/FOSRestBundle#2059]
1.
>  2x: Calling "Symfony\Bundle\FrameworkBundle\Test\WebTestCase::createClient()" while a kernel has been booted is deprecated since Symfony 4.4 and will throw in 5.0, ensure the kernel is shut down before calling the method.
>    1x in SerializerErrorTest::testSerializeExceptionJson from FOS\RestBundle\Tests\Functional
>    1x in ViewResponseListenerTest::testRedirect from FOS\RestBundle\Tests\Functional

2.
>  12x: The "controller_name_converter" service is deprecated since Symfony 4.3. It is being referenced by the "fos_rest.routing.loader.controller" service.

3.
>   1x: The template "@Twig/layout.html.twig" is deprecated since Symfony 4.4, will be removed in 5.0. ("@Twig/layout.html.twig" at line 1).
    1x in ConfigurationTest::testToolbar from FOS\RestBundle\Tests\Functional

>   1x: The template "@Twig/exception.css.twig" is deprecated since Symfony 4.4, will be removed in 5.0. ("@Twig/exception.css.twig" at line 1).
    1x in ConfigurationTest::testToolbar from FOS\RestBundle\Tests\Functional

>   1x: The template "@Twig/base_js.html.twig" is deprecated since Symfony 4.4, will be removed in 5.0. ("@Twig/base_js.html.twig" at line 1).
    1x in ConfigurationTest::testToolbar from FOS\RestBundle\Tests\Functional

>   1x: The "twig.controller.preview_error" service is deprecated since Symfony 4.4.
    1x in RequestBodyParamConverterTest::testTwigErrorPage from FOS\RestBundle\Tests\Functional

>   1x: The "Symfony\Bundle\TwigBundle\Controller\PreviewErrorController" class is deprecated since Symfony 4.4, use the "Symfony\Component\HttpKernel\Controller\ErrorController" instead.
    1x in RequestBodyParamConverterTest::testTwigErrorPage from FOS\RestBundle\Tests\Functional

**Comment by wumke** [comment]
2. is fixed by https://github.com/FriendsOfSymfony/FOSRestBundle/pull/2036 (and mentioned in changelog for 2.7: 'fixed DisableCSRFExtension::getExtendedTypes() return type' )

**Comment by morki** [comment]
@wumke @XWB I am installing dev-master@dev and `The "controller_name_converter" service is deprecated since Symfony 4.3. It is being referenced by the "fos_rest.routing.loader.controller" service.` is still not fixed. Is there something I need to do in configuration?

**Comment by XWB** [comment]
@wumke The deprecation notice was a copy/paste from the master branch, so it is not entirely fixed.

**Comment by xabbuh** [comment]
all the deprecations are fixed now and I tagged the 2.7.0 release

**Comment by kevinpapst** [comment]
Nr 2 (the `controller_name_converter` deprecation) is still available in 2.7.0 here. The possible fix that was [available](https://github.com/FriendsOfSymfony/FOSRestBundle/pull/2032/files#diff-ffb88a00253e285e14e0d32ef5423cd1R96) in #2032 was closed in favor of #2036 but not applied there

**Comment by xabbuh** [comment]
@kevinpapst see #2074
